services:
  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    restart: always
    networks:
      - nexus3_net
    ports:
      - "8081:8081"
    volumes:
      - ./data:/nexus-data
networks:
  nexus3_net:
    driver: bridge