services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf  # 挂载配置文件
      - ./log:/var/log/nginx                      # 挂载日志目录
      - ./html:/usr/share/nginx/html              # 挂载静态文件目录
    ports:
      - "80:80"
#      - "443:443"  # 如果需要HTTPS，可以开启443端口
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
